# This workflow test the code.

name: Code testing

on:
  push:
    branches:
      - development
      - dev-actions-1
  workflow_dispatch:

jobs:
  testing:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - env:
          TWITCH_TOKEN: ${{ secrets.TWITCH_TOKEN }}
        run: npm run test
