# This workflow test the code.

name: Code testing

on:
  push:
    branches:
      - development
      - dev-actions-1
  workflow_dispatch:

jobs:
  testing:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 23

      - run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 \
            libx11-xcb1 \
            libxcomposite1 \
            libxrandr2 \
            libgbm1 \
            wget \
            curl \
            ca-certificates \
            fonts-liberation \
            libappindicator3-1 \
            libasound2 \
            libnspr4


      - run: npm ci
      - run: npm run webpack_test
      - run: cp src/OBSTwitchChat.html dist/OBSTwitchChat.html
      - env:
          TWITCH_TOKEN: ${{ secrets.TWITCH_TOKEN }}
        run: npm run test
